SongsSRC = [
"4 Non Blondes|WHAT'S UP|https://open.spotify.com/track/0jWgAnTrNZmOGmqgvHhZEm|83|46",
"Adam Clayton, Larry Mullen Jr.|MISSION IMPOSSIBLE THEME|https://open.spotify.com/track/2BVueDW1REKHYpWkB9KbDF|221|N",
"Adele|HELLO|https://open.spotify.com/track/1Yk0cQdMLx5RzzFTYwmuld|78|N",
"Adele|ROLLING IN THE DEEP|https://open.spotify.com/track/4OSBTYWVwsQhGLF9NHvIbR|223|7",
"Adele|SKYFALL|https://open.spotify.com/track/6VObnIkLVruX4UVyxWhlqm|49|N",
"Adele|SOMEONE LIKE YOU|https://open.spotify.com/track/3bNv3VuUOKgrf5hu3YcuRo|120|-15",
"Aerosmith|CRAZY|https://open.spotify.com/track/74irxdVWstNlEQjsvArITq|155|-28",
"a-ha|LIFELINES|https://open.spotify.com/track/3kPuHm2aXRJvpoKOCtjYI0|27|222",
"a-ha|SUMMER MOVED ON|https://open.spotify.com/track/6xt09pCFANiwzrTfhyQ1mC|133|132",
"Air feat. Beth Hirsch|ALL I NEED|https://open.spotify.com/track/6T10XPeC9X5xEaD6tMcK6M|229|N",
"Airbag|COLOURS|https://open.spotify.com/track/7dgawv4BuQEVmpoRp1Z0sN|74|N",
"Alan Parsons|AS LIGHTS FALL |https://open.spotify.com/track/59Nv0s5k8TL5aa0xFXkwyl|NOWOŚĆ|N",
"Alanis Morissette|IRONIC|https://open.spotify.com/track/4oGTdOClZUxcM2H3UmXlwL|72|50",
"Alice In Chains|I STAY AWAY|https://open.spotify.com/track/6HnZsLUDrG3HTSbh8sq2u3|NOWOŚĆ|N",
"Amy Winehouse|BACK TO BLACK|https://open.spotify.com/track/30FURVTCpbKyykjSEQzGkH|203|N",
"Amy Winehouse|REHAB|https://open.spotify.com/track/3N4DI1vuTSX1tz7fa2NQZw|148|-40",
"Amy Winehouse|YOU KNOW I'M NO GOOD|https://open.spotify.com/track/0DMRKqrpd0QO4RWiEdMib0|140|-31",
"Anathema|FRAGILE DREAMS|https://open.spotify.com/track/7EExKNitXoRvmPwZy0hbPO|108|N",
"Andrea Bocelli, Sarah Brightman|TIME TO SAY GOODBYE|https://open.spotify.com/track/4aLcGMxwFtcZRpl7NDtNW2|232|62",
"Aphex Twin|ALBERTO BALSALM|https://open.spotify.com/track/21Phj46KeUHOWyZW9A9b7P|111|N",
"Arcade Fire|REFLEKTOR|https://open.spotify.com/track/4bX1HlRP3e9aTZ6aNOfnzL|NOWOŚĆ|N",
"Archive|AGAIN|https://open.spotify.com/track/68hIkZXqCrkdsugmX6zs6W|2|0",
"Archive|FUCK U|https://open.spotify.com/track/34ebeHWIGQrAt99L1R2Kyn|NOWOŚĆ|N",
"Arctic Monkeys|505|https://open.spotify.com/track/0BxE4FqsDD1Ot4YuBXwAPp|192|N",
"Arctic Monkeys|A CERTAIN ROMANCE|https://open.spotify.com/track/0eDQj41kzBhMKQIkTt6OJR|70|N",
"Arctic Monkeys|DO I WANNA KNOW?|https://open.spotify.com/track/5FVd6KXrgO9B3JPmC8OPst|16|N",
"Arctic Monkeys|I BET YOU LOOK GOOD ON THE DANCEFLOOR|https://open.spotify.com/track/3DQVgcqaP3iSMbaKsd57l5|71|-20",
"Ayo, Youssoupha|FIRE|https://open.spotify.com/track/6gYpqMBJUGFxkXEus4PVQL|NOWOŚĆ|N",
"Banco de Gaia|LAST TRAIN TO LHASA|https://open.spotify.com/track/2Joozdms9UpsRjAUdHP8Fo|NOWOŚĆ|N",
"Band of Horses|THE FUNERAL|https://open.spotify.com/track/5lRzWDEe7UuedU2QPsFg0K|NOWOŚĆ|N",
"Bang Gang|INSIDE|https://open.spotify.com/track/76fLNi64MTonSw7esUYvno|204|N",
"The Beach Boys|THAT'S WHY GOD MADE THE RADIO|https://open.spotify.com/track/7bmiIJ98JjFCNwH27LUKSv|58|N",
"Beastie Boys|SABOTAGE|https://open.spotify.com/track/0Puj4YlTm6xNzDDADXHMI9|13|115",
"Beirut|POSTCARDS FROM ITALY|https://open.spotify.com/track/7H0UxIN751StFi2tznmHlg|194|-144",
"Belleruche|ANYTHING YOU WANT - NOT THAT|https://open.spotify.com/track/6sI5m6cabkKWBuDh0kXMKk|NOWOŚĆ|N",
"Beth Hart|CAUGHT OUT IN THE RAIN|https://open.spotify.com/track/7nAlg457jECNXuwbxMRkPB|51|N",
"Birds of Tokyo|TALKING TO A STRANGER|https://open.spotify.com/track/7plBALE90Sn1qCGIIyOvvb|191|N",
"Björk|HUMAN BEHAVIOUR|https://open.spotify.com/track/6Kz3o55LxMA11GbvFXHFtX|73|239",
"Björk|IT'S OH SO QUIET|https://open.spotify.com/track/3CMVjlbvNJMHDfYPX7xCpi|211|85",
"The Black Keys|BLACK DOOR|https://open.spotify.com/track/4Itg0GtVXzHPK48JkKRkmH|236|N",
"The Black Keys|LONELY BOY|https://open.spotify.com/track/5G1sTBGbZT5o4PNRc75RKI|NOWOŚĆ|N",
"Blackfield|END OF THE WORLD|https://open.spotify.com/track/2AmGtOFvBOISnmXJ7BJpnP|149|86",
"Blur|SONG 2|https://open.spotify.com/track/1FTSo4v6BOZH9QxKc3MbVM|150|138",
"Blur|TENDER|https://open.spotify.com/track/42cxPm9jgbaxIVN77XA1m6|196|78",
"Bon Jovi|IT'S MY LIFE|https://open.spotify.com/track/0v1XpBHnsbkCn7iJ9Ucr1l|35|231",
"Bruce Springsteen|STREETS OF PHILADELPHIA|https://open.spotify.com/track/6WgBIPHwkQhCqMNnR5hQCN|3|127",
"Bullet for My Valentine|TEARS WON'T FALL|https://open.spotify.com/track/5pKCDm2fw4k6D6C5Rk646C|NOWOŚĆ|N",
"Bush|THE PEOPLE THAT WE LOVE|https://open.spotify.com/track/6smnMpZoSuesKjFbbGg9VI|NOWOŚĆ|N",
"C418|SWEDEN|https://open.spotify.com/track/4NsPgRYUdHu2Q5JRNgXYU5|42|N",
"The Cardigans|ERASE/REWIND|https://open.spotify.com/track/3JfkNCiXjHEVkbFfCQ417E|228|N",
"Céline Dion|MY HEART WILL GO ON|https://open.spotify.com/track/33LC84JgLvK2KuW43MfaNq|130|159",
"Charlotte Gainsbourg feat. Beck|HEAVEN CAN WAIT|https://open.spotify.com/track/5FrbEiNS4IT5AAlU60XoVn|137|N",
"The Chemical Brothers|GALVANIZE|https://open.spotify.com/track/4bz7uB4edifWKJXSDxwHcs|41|-8",
"The Chemical Brothers|HEY BOY HEY GIRL|https://open.spotify.com/track/7kXmJwrZGIhDaLT9sNo3ut|NOWOŚĆ|N",
"Christine and the Queens|TILTED|https://open.spotify.com/track/2ILilOGEh31uHITYFazrLM|227|N",
"Cigarettes After Sex|HEAVENLY|https://open.spotify.com/track/70YTBH8vOGJNMhy6186yFm|98|N",
"Club des Belugas, Ester Rada|SAVE A LITTLE LOVE FOR ME|https://open.spotify.com/track/6lqxlJWNaykLli5cIXMf7l|NOWOŚĆ|N",
"Coldplay|CLOCKS|https://open.spotify.com/track/0BCPKOYdS2jbQ8iyB56Zns|141|109",
"Coldplay|IN MY PLACE|https://open.spotify.com/track/2nvC4i2aMo4CzRjRflysah|210|41",
"Coldplay|THE SCIENTIST|https://open.spotify.com/track/75JFxkI2RXiU7L9VXzMkle|89|163",
"Coverdale and Page|TAKE ME FOR A LITTLE WHILE|https://open.spotify.com/track/63IYBrppd22mLuFvOQUAkR|117|N",
"The Cranberries|ANIMAL INSTINCT|https://open.spotify.com/track/3J58Ccc5iTbCRnYx2xjo6d|25|254",
"The Cranberries|LINGER|https://open.spotify.com/track/0gEyKnHvgkrkBM6fbeHdwK|205|N",
"The Cranberries|ZOMBIE|https://open.spotify.com/track/7EZC6E7UjZe63f1jRmkWxt|62|-44",
"Crash Test Dummies|MMM MMM MMM MMM|https://open.spotify.com/track/31v2AQlx4pDI7kmnLxBkem|132|-1",
"Daft Punk|ONE MORE TIME|https://open.spotify.com/track/0DiWol3AO6WpXZgp0goxAV|24|10",
"Daft Punk|GIORGIO BY MORODER|https://open.spotify.com/track/0oks4FnzhNp5QPTZtoet7c|NOWOŚĆ|N",
"Daft Punk feat. Pharrell Williams, Nile Rodgers|GET LUCKY|https://open.spotify.com/track/69kOkLUCkxIZYexIgSG8rq|23|9",
"Daft Punk, Julian Casablancas|INSTANT CRUSH|https://open.spotify.com/track/2cGxRwrMyEAp8dEbuZaVv6|NOWOŚĆ|N",
"Damien Rice|THE BLOWER'S DAUGHTER|https://open.spotify.com/track/5yyRH93h4Pm6tXXYTxt7ea|188|68",
"Darude|SANDSTORM|https://open.spotify.com/track/3gyYkQZkgJ3skbCmseIK7P|NOWOŚĆ|N",
"Dave Matthews Band|FUNNY THE WAY IT IS|https://open.spotify.com/track/3gl3iordKdC2upWvHWbfie|178|54",
"Dave Matthews Band|WHY I AM|https://open.spotify.com/track/0gbfxMX9jfGd1eEaqwhugx|NOWOŚĆ|N",
"David Bowie|LAZARUS|https://open.spotify.com/track/7rFN0DhIFPjAWG1EaHO2F0|8|N",
"David Bowie|WHERE ARE WE NOW?|https://open.spotify.com/track/47IRJtymREDMhW3fn2Hj0T|NOWOŚĆ|N",
"Dead Can Dance|OPIUM|https://open.spotify.com/track/7bhKtEjtvHgp7lQtlfJdDb|NOWOŚĆ|N",
"Depeche Mode|IT'S NO GOOD|https://open.spotify.com/track/7HDWE2Ib7cjkhzULV4K8y3|32|N",
"Depeche Mode|MERCY IN YOU|https://open.spotify.com/track/637PXsKq2k2BTugVRA20ZV|43|N",
"Depeche Mode|WALKING IN MY SHOES|https://open.spotify.com/track/2Y7ndoyiIm0IaFJa13gV3H|NOWOŚĆ|N",
"Depeche Mode|RUSH|https://open.spotify.com/track/0WWn01c1xisnbTKStjLiY2|NOWOŚĆ|N",
"Dido|HERE WITH ME|https://open.spotify.com/track/4xFxK0FXmNlUDRgCaIQCVn|231|44",
"Dido|WHITE FLAG|https://open.spotify.com/track/6si71supnBUhddjR2FJc2L|225|20",
"DJ Shadow|BUILDING STEAM WITH A GRAIN OF SALT|https://open.spotify.com/track/4Ms0GKHCtr5Lpg4dKOhO2I|110|N",
"DJ Shadow|GIVING UP THE GHOST|https://open.spotify.com/track/4HzN6LNHCz294iqHkekFX5|174|N",
"DragonForce|THROUGH THE FIRE AND FLAMES|https://open.spotify.com/track/1UMdbkqX19OiwfExH7gzYA|92|N",
"Dua Lipa|COOL|https://open.spotify.com/track/2nMOodYNHBAQ3Kc1QNimZU|NOWOŚĆ|N",
"Eddie Vedder|INVINCIBLE|https://open.spotify.com/track/7pv5juhfq1kco6wioikGHt|NOWOŚĆ|N",
"Elton John|BELIEVE|https://open.spotify.com/track/0mh3kdiViRyeH8JzVL61Hw|36|N",
"Elton John|MADE IN ENGLAND|https://open.spotify.com/track/6VmxhbNRCURgu8d5pEPRb8|185|N",
"Eminem|LOSE YOURSELF|https://open.spotify.com/track/5Z01UMMf7V1o0MzF86s6WJ|50|N",
"Eminem|WITHOUT ME|https://open.spotify.com/track/2YaiY5Cr8IFv0X0YRZDNzV|195|-78",
"Eminem feat. Dido|STAN|https://open.spotify.com/track/3UmaczJpikHgJFyBTAJVoz|54|3",
"Enya|MAY IT BE|https://open.spotify.com/track/7LAJWSKK8JMIZAcblgUMS6|216|41",
"Eric Clapton|MY FATHER'S EYES|https://open.spotify.com/track/2GGskYwS4j8LDMSDUJ8vrl|77|N",
"Eric Clapton|CHANGE THE WORLD|https://open.spotify.com/track/5Ds0VGkTSQ1jf4KzLUpZPb|NOWOŚĆ|N",
"Evanescence|BRING ME TO LIFE|https://open.spotify.com/track/0COqiPhxzoWICwFCS4eZcp|209|37",
"Evanescence|MY IMMORTAL|https://open.spotify.com/track/3PYdxIDuBIuJSDGwfptFx4|NOWOŚĆ|N",
"Everything But the Girl|MISSING|https://open.spotify.com/track/1LLYmUrNeb77HTwtr4e2Wr|107|196",
"Faith No More|EVIDENCE|https://open.spotify.com/track/0cLH7BXqfm0RqnjueCPLfW|112|N",
"Faithless|INSOMNIA|https://open.spotify.com/track/5z5wYWL1IO6y2yEFBOiGt0|164|-41",
"Faithless|MASS DESTRUCTION|https://open.spotify.com/track/4qaXLuojUaHRmiSbTbmUDg|53|N",
"Falco|OUT OF THE DARK|https://open.spotify.com/track/6vgnumRgsZcc5fVFtpIRO1|NOWOŚĆ|N",
"Fastball|THE WAY|https://open.spotify.com/track/7IsEXPk6qqt30FfQv4SZMa|208|N",
"Fatboy Slim|RIGHT HERE, RIGHT NOW|https://open.spotify.com/track/5Sh9v7RwibuV34tdjscwx5|129|152",
"Flogging Molly|MAY THE LIVING BE DEAD (IN OUR WAKE)|https://open.spotify.com/track/3RkQe0mlyTdTKiXGv385F0|NOWOŚĆ|N",
"Florence and the Machine|RABBIT HEART (RAISE IT UP)|https://open.spotify.com/track/5jAYbBuwroXXigCj4IGFdA|200|N",
"Florence and the Machine|WHAT KIND OF MAN|https://open.spotify.com/track/2kP1ujXHn0mNqFbiT3zob8|99|N",
"Florence and the Machine|KING|https://open.spotify.com/track/1VSngtLdJhrlfHkLxTyOXK|NOWOŚĆ|N",
"Fontaines D.C.|I LOVE YOU|https://open.spotify.com/track/4N8idxy0W2GDaEosAwPOMg|NOWOŚĆ|N",
"Foo Fighters|EVERLONG|https://open.spotify.com/track/5UWwZ5lm5PKu6eKsHAGxOk|176|N",
"Foo Fighters|MY HERO|https://open.spotify.com/track/4dVbhS6OiYvFikshyaQaCN|109|N",
"Foo Fighters|ROPE|https://open.spotify.com/track/7v0mtl6oInUtHOmTk2b0gC|235|N",
"Foo Fighters|THE PRETENDER|https://open.spotify.com/track/7x8dCjCr0x6x2lXKujYD34|6|9",
"Foo Fighters|LOVE DIES YOUNG|https://open.spotify.com/track/5suO1J3cXSVWJ7ED3kasKQ|NOWOŚĆ|N",
"Franz Ferdinand|TAKE ME OUT|https://open.spotify.com/track/20I8RduZC2PWMWTDCZuuAN|12|41",
"Fun Lovin' Criminals|SCOOBY SNACKS|https://open.spotify.com/track/7I8KtOFPNmC2ZsiNPCwoS8|NOWOŚĆ|N",
"Garbage|SUPERVIXEN|https://open.spotify.com/track/6xeZe41asrgdgWg4ri7r1r|NOWOŚĆ|N",
"Gary Jules|MAD WORLD|https://open.spotify.com/track/3JOVTQ5h8HGFnDdp4VT3MP|172|86",
"Gazpacho|UPSIDE DOWN|https://open.spotify.com/track/69xUkf647IyVn8cJtQ4zRk|202|N",
"Godspeed You! Black Emperor|STORM|https://open.spotify.com/track/1HfJV18PHF2UQqh4TuySBJ|102|N",
"Goran Bregović|KALASNJIKOV|https://open.spotify.com/track/6OlCJxmWri50RLA1CrBYZ6|65|59",
"Gorillaz|CLINT EASTWOOD|https://open.spotify.com/track/1RKUoGiLEbcXN4GY4spQDx|219|-101",
"Gorillaz|DARE|https://open.spotify.com/track/4Hff1IjRbLGeLgFgxvHflk|125|114",
"Gorillaz|FEEL GOOD INC.|https://open.spotify.com/track/0d28khcov6AiegSCpG5TuT|29|N",
"Gorillaz|ON MELANCHOLY HILL|https://open.spotify.com/track/0q6LuUqGLUiCPP1cbdwFs3|166|N",
"Gorillaz|JIMMY JIMMY|https://open.spotify.com/track/4Iv2jOCKQakC3YWhijrRKK|NOWOŚĆ|N",
"Gorillaz, Tame Impala|NEW GOLD|https://open.spotify.com/track/64dLd6rVqDLtkXFYrEUHIU|NOWOŚĆ|N",
"Gotye|HEARTS A MESS|https://open.spotify.com/track/4nPzk1lhLWmQUX7tM94KZL|116|121",
"Gotye feat. Kimbra|SOMEBODY THAT I USED TO KNOW|https://open.spotify.com/track/1qDrWA6lyx8cLECdZE7TV7|97|132",
"Green Day|AMERICAN IDIOT|https://open.spotify.com/track/6nTiIhLmQ3FWhvrGafw2zj|187|-77",
"Green Day|BOULEVARD OF BROKEN DREAMS|https://open.spotify.com/track/1hwJKpe0BPUsq6UUrwBWTw|214|-103",
"Greta Van Fleet|AGE OF MACHINE|https://open.spotify.com/track/6XALorRRo9aQdBIQN0UWyn|57|N",
"Guano Apes|LORDS OF THE BOARDS|https://open.spotify.com/track/54Kox6D5c5JNW9ujt3hcOW|NOWOŚĆ|N",
"Harry Styles|TREAT PEOPLE WITH KINDNESS|https://open.spotify.com/track/03mMSLEJCPoGJwQhHpN5y0|NOWOŚĆ|N",
"Hozier|TAKE ME TO CHURCH|https://open.spotify.com/track/3dYD57lRAUcMHufyqn9GcI|NOWOŚĆ|N",
"Hybrid|DISAPPEAR HERE|https://open.spotify.com/track/6BkDdBhOuNb7Lkv88GTsAd|154|N",
"IAMX|THINK OF ENGLAND|https://open.spotify.com/track/5JwTp6CLbYQD6JPcJVqs3Y|144|N",
"Jack Savoretti|YOU DON'T HAVE TO SAY YOU LOVE ME / IO CHE NON VIVO SENZA TE|https://open.spotify.com/track/2VPhNiZZZS0tmVukzgBoOA|NOWOŚĆ|N",
"Jack White|TAKING ME BACK|https://open.spotify.com/track/37FjxvMhMjt3YRecpx7HsC|NOWOŚĆ|N",
"Jack White, Alicia Keys|ANOTHER WAY TO DIE|https://open.spotify.com/track/01bMpqmvH031R417l3AQTA|220|13",
"James|LAID|https://open.spotify.com/track/2CdS3DRqWR5LAhy4hM5X9W|NOWOŚĆ|N",
"Jamiroquai|VIRTUAL INSANITY|https://open.spotify.com/track/24SUWisv2lYQiB3bVpE1sn|163|-102",
"Jay-Z, Alicia Keys|EMPIRE STATE OF MIND|https://open.spotify.com/track/2igwFfvr1OAGX9SKDCPBwO|NOWOŚĆ|N",
"Jeff Buckley|HALLELUJAH|https://open.spotify.com/track/3pRaLNL3b8x5uBOcsgvdqM|190|114",
"Joe Bonamassa|DRIVE|https://open.spotify.com/track/2knqdlYKjS0J27lYyyRllU|136|N",
"Joe Bonamassa, Beth Hart|I'LL TAKE CARE OF YOU|https://open.spotify.com/track/644oQEcMNmA3ABAOrfY7k3|NOWOŚĆ|N",
"Johnny Cash|HURT|https://open.spotify.com/track/5rpRzNcJZqKQXk9PIjreB6|17|38",
"Judas Priest|LIGHTNING STRIKE|https://open.spotify.com/track/6qopop1Rc9r1RjEIBQhc8d|NOWOŚĆ|N",
"Junior Senior|MOVE YOUR FEET|https://open.spotify.com/track/4DX82Vc8qAH4jJPvKxvwg6|NOWOŚĆ|N",
"Kaiser Chiefs|RUBY|https://open.spotify.com/track/2sgBTNHz9ckmqj3rx3ez4M|121|115",
"Katie Melua|NINE MILLION BICYCLES|https://open.spotify.com/track/0xQdisF8CHkso4LnJcaIMr|126|114",
"Katie Melua|SPIDER'S WEB|https://open.spotify.com/track/47R2P5dRucrGOkPj7BSbF2|86|155",
"Kavinsky|NIGHTCALL|https://open.spotify.com/track/0U0ldCRmgCqhVvD6ksG63j|52|N",
"The Killers|MR. BRIGHTSIDE|https://open.spotify.com/track/003vvx7Niy0yvhvHt4a68B|183|N",
"The Killers|SOMEBODY TOLD ME|https://open.spotify.com/track/6PwjJ58I4t7Mae9xfZ9l9v|171|-58",
"Kings Of Leon|SEX ON FIRE|https://open.spotify.com/track/0ntQJM78wzOLVeCUAW7Y45|224|10",
"Kings Of Leon|USE SOMEBODY|https://open.spotify.com/track/5VGlqQANWDKJFl0MBG3sg2|124|-17",
"KoRn|FREAK ON A LEASH|https://open.spotify.com/track/6W21LNLz9Sw7sUSNWMSHRu|175|N",
"Kreator|SATAN IS REAL|https://open.spotify.com/track/14M68PdZSSMRzTBuJNuxO6|NOWOŚĆ|N",
"Lacrimosa|SANCTUS|https://open.spotify.com/track/1UN4BDeC8nQONxDTGOj4Fl|167|N",
"The Last Shadow Puppets|MIRACLE ALLIGNER|https://open.spotify.com/track/4iwpCp7qdDLngGI3gsVTza|94|N",
"Last Train|FIRE|https://open.spotify.com/track/7EZXYslJB5VZUbGma0kt9c|234|N",
"The Legendary Pink Dots|LENT|https://open.spotify.com/track/7DI5OICsSjolozyNNNKRwl|NOWOŚĆ|N",
"Linkin Park|IN THE END|https://open.spotify.com/track/60a0Rd6pjrkxjPbaKzXjfq|68|-10",
"Linkin Park|NUMB|https://open.spotify.com/track/2nLtzopw4rPReszdYBJU6h|67|-13",
"M83|MIDNIGHT CITY|https://open.spotify.com/track/6GyFP1nfCDB8lbD2bG0Hq9|NOWOŚĆ|N",
"Madonna|FROZEN|https://open.spotify.com/track/2II03llydk4YnkBBvoYB3B|10|274",
"Madonna|HUNG UP|https://open.spotify.com/track/3850dYVgOFIXJh5U4BFEWH|179|63",
"Madonna|TAKE A BOW|https://open.spotify.com/track/7izFzcBTx3DVXFeFYDeZKB|158|147",
"Marillion|THIS IS THE 21ST CENTURY|https://open.spotify.com/track/5FAootOMJfwyXPovGelhQ7|230|30",
"Mark Knopfler|WHAT IT IS|https://open.spotify.com/track/65f8Ca4HbZCMLhpZPTHW4O|134|136",
"Mark Knopfler|WHY AYE MAN|https://open.spotify.com/track/7BujMCC8IhoBorzOgBnj88|160|N",
"Mark Knopfler|SAILING TO PHILADELPHIA|https://open.spotify.com/track/5N6GzBkdnHcaH96R6aJQHm|NOWOŚĆ|N",
"Massive Attack|TEARDROP|https://open.spotify.com/track/36G7q9VtOVEYhuALFcO04W|5|12",
"Mastodon|THE LAST BARON|https://open.spotify.com/track/6MUc3qu8WOqO7hAY6gdhJY|NOWOŚĆ|N",
"Meat Loaf|I'D DO ANYTHING FOR LOVE (BUT I WON'T DO THAT)|https://open.spotify.com/track/4UrgDocbHywDZv2f3mBhCq|114|-48",
"Metallica|THE DAY THAT NEVER COMES|https://open.spotify.com/track/13Uvqll8OQDjw3wDweIK9y|182|N",
"Metallica|UNTIL IT SLEEPS|https://open.spotify.com/track/2Iv4HSoMX2fDeXFcOJWyWX|31|N",
"Metallica|WHISKEY IN THE JAR|https://open.spotify.com/track/2R6UrJ8uWbSIiHWmvRQvN8|56|229",
"Metallica|Lux Æterna|https://open.spotify.com/track/0QfZ8OHFnFzLe66iFBww2U|NOWOŚĆ|N",
"Metallica|HALO ON FIRE|https://open.spotify.com/track/3HZP4wlFGbxHtErgM0IGCZ|NOWOŚĆ|N",
"Metronomy|THE LOOK|https://open.spotify.com/track/6zfczP87XO2SxWlQtnjFNa|118|N",
"Mew|COMFORTING SOUNDS|https://open.spotify.com/track/3Nz6SzfpsCa7LJLDTNiq9C|197|N",
"MGMT|KIDS|https://open.spotify.com/track/1jJci4qxiYcOHhQR247rEU|75|N",
"MGMT|LITTLE DARK AGE|https://open.spotify.com/track/2Y0iGXY6m6immVb2ktbseM|NOWOŚĆ|N",
"Michael Jackson|EARTH SONG|https://open.spotify.com/track/4GCGH6TJ69neckwITeBFXK|233|64",
"Michael Kiwanuka|COLD LITTLE HEART|https://open.spotify.com/track/0qprlw0jfsW4H9cG0FFE0Z|NOWOŚĆ|N",
"Modjo|LADY (HEAR ME TONIGHT)|https://open.spotify.com/track/49X0LAl6faAusYq02PRAY6|NOWOŚĆ|N",
"Muse|KNIGHTS OF CYDONIA|https://open.spotify.com/track/7ouMYWpwJ422jRcDASZB7P|101|N",
"Muse|MADNESS|https://open.spotify.com/track/0c4IEciLCDdXEhhKxj4ThA|173|N",
"Muse|UPRISING|https://open.spotify.com/track/4VqPOruhp5EdPBeR92t6lQ|79|27",
"Muse|CITIZEN ERASED|https://open.spotify.com/track/177MZraDAxjRqqtZBz5Vhn|NOWOŚĆ|N",
"Muse|WE ARE FUCKING FUCKED|https://open.spotify.com/track/5IumuUJqNO7K5SvniuDrBz|NOWOŚĆ|N",
"Nick Cave and the Bad Seeds|DO YOU LOVE ME?|https://open.spotify.com/track/4ZHENvl0Jvmda9mVqYM9JI|66|241",
"Nick Cave and the Bad Seeds|INTO MY ARMS|https://open.spotify.com/track/39CFOvYse9fcMhIwyS73Fl|69|N",
"Nick Cave and the Bad Seeds|RED RIGHT HAND|https://open.spotify.com/track/0jVo3e34A15l6MNu1O3cfa|20|N",
"Nick Cave, Kylie Minogue|WHERE THE WILD ROSES GROW|https://open.spotify.com/track/4LK8kGGY0FGSGIAk2GwI30|115|10",
"Nightwish|NEMO|https://open.spotify.com/track/1RNwniZkJqdw9LMkkyynjx|217|N",
"Nightwish|THE PHANTOM OF THE OPERA|https://open.spotify.com/track/6VOxRb9IAJQDDyHBlyEdPF|237|N",
"Nightwish|WISH I HAD AN ANGEL|https://open.spotify.com/track/6IKk2Z7LO59UDnVEw8JCBj|87|N",
"Nine Inch Nails|CLOSER|https://open.spotify.com/track/5mc6EyF1OIEOhAkD0Gg9Lc|218|N",
"Nine Inch Nails|HURT|https://open.spotify.com/track/27tX58NOpv1YKQ0abW7EPy|165|143",
"Nirvana|HEART-SHAPED BOX|https://open.spotify.com/track/11LmqTE2naFULdEP94AUBa|180|134",
"No Doubt|DON'T SPEAK|https://open.spotify.com/track/6urCAbunOQI4bLhmGpX7iS|90|208",
"Oasis|DON'T LOOK BACK IN ANGER|https://open.spotify.com/track/0UvCh63URrLFcPkKt99hHd|28|35",
"The Offspring|PRETTY FLY (FOR A WHITE GUY)|https://open.spotify.com/track/3SFXsFpeGmBTtQvKiwYMDA|222|-102",
"The Offspring|SELF ESTEEM|https://open.spotify.com/track/1FkoVC85Ds3mFoK0fVqEqP|177|-140",
"Outkast|HEY YA!|https://open.spotify.com/track/2PpruBYCo4H7WOBJ7Q2EwM|156|91",
"Ozzy Osbourne|DREAMER|https://open.spotify.com/track/78PKCefXwDLbl4FVO1Pjzh|NOWOŚĆ|N",
"Pearl Jam|CRAZY MARY|https://open.spotify.com/track/1jxXMshk2V5r7CHSurIKZS|47|269",
"Pearl Jam|DANCE OF THE CLAIRVOYANTS|https://open.spotify.com/track/3Y1q37A7ecFEdR5IAMWodA|153|N",
"Pearl Jam|JUST BREATHE|https://open.spotify.com/track/6i81qFkru6Kj1IEsB7KNp2|61|N",
"Pearl Jam|GIVEN TO FLY|https://open.spotify.com/track/3vL9lPWBuv0ZR3c5YmdhDl|NOWOŚĆ|N",
"Phantogram|WHEN I'M SMALL|https://open.spotify.com/track/3y1EzRl5UEQxxd1f6Bv2aN|201|N",
"Phil Collins|YOU'LL BE IN MY HEART|https://open.spotify.com/track/4Y8vb1uy9IjM2V1hqvrAid|NOWOŚĆ|N",
"Pink Floyd|HIGH HOPES|https://open.spotify.com/track/236mI0lz8JdQjlmijARSwY|1|35",
"Placebo|ASHTRAY HEART|https://open.spotify.com/track/2yYASbXnAV71CLbNY1HCWf|207|N",
"Placebo|THE BITTER END|https://open.spotify.com/track/2yYASbXnAV71CLbNY1HCWf|96|20",
"Placebo, David Bowie|WITHOUT YOU I'M NOTHING|https://open.spotify.com/track/7vQmo763FvSQoVuLohIzRb|226|50",
"Porcupine Tree|ANESTHETIZE|https://open.spotify.com/track/2VvUor8pk8HOR9cb5iC84z|81|N",
"Porcupine Tree|LAZARUS|https://open.spotify.com/track/0OtXJQBLb7wPXL2XyN2cFW|199|44",
"Porcupine Tree|TRAINS|https://open.spotify.com/track/7HK4RUHg3xmihjjjkO1Pse|NOWOŚĆ|N",
"Porcupine Tree|LIGHTBULB SUN|https://open.spotify.com/track/04Vcsh7Cexb2bmVpS7FLrR|NOWOŚĆ|N",
"Portishead|GLORY BOX|https://open.spotify.com/track/3Ty7OTBNSigGEpeW2PqcsC|105|-41",
"Portishead|ROADS|https://open.spotify.com/track/2sW8fmnISifQTRgnRrQTYW|170|N",
"The Prodigy|FIRESTARTER|https://open.spotify.com/track/79CUrU5o2KAVDTNm4x3eGU|104|-42",
"The Prodigy|BREATHE|https://open.spotify.com/track/0Ja4hLKiUSw01E01pJ1yGr|122|173",
"Pulp|COMMON PEOPLE|https://open.spotify.com/track/2fXKyAyPrEa24c6PJyqznF|39|87",
"Quantic|THE 5TH EXOTIC|https://open.spotify.com/track/62iRNRNRD0dqp2UbuSNPVn|NOWOŚĆ|N",
"Queens of the Stone Age|LITTLE SISTER|https://open.spotify.com/track/1rzYrkxgRuLLJDqWdB32pK|193|N",
"Queens of the Stone Age|NO ONE KNOWS|https://open.spotify.com/track/6y20BV5L33R8YXM0YuI38N|63|-7",
"Queens of the Stone Age|I APPEAR MISSING|https://open.spotify.com/track/0Dv8OfSPwrXmNNbE70b9Dq|NOWOŚĆ|N",
"Radiohead|BURN THE WITCH|https://open.spotify.com/track/3DpuYpzkvUWXbmzCm6pfzR|206|N",
"Radiohead|FAKE PLASTIC TREES|https://open.spotify.com/track/73CKjW3vsUXRpy3NnX4H7F|46|N",
"Radiohead|KARMA POLICE|https://open.spotify.com/track/63OQupATfueTdZMWTxW03A|82|39",
"Radiohead|NO SURPRISES|https://open.spotify.com/track/10nyNJ6zNy2YVYLrcwLccB|151|140",
"Radiohead|WEIRD FISHES/ARPEGGI|https://open.spotify.com/track/4wajJ1o7jWIg62YqpkHC7S|NOWOŚĆ|N",
"Rage Against the Machine|GUERILLA RADIO|https://open.spotify.com/track/1wsRitfRRtWyEapl0q22o8|88|N",
"Rammstein|AMERIKA|https://open.spotify.com/track/1a8JpAL3vbAdXYrEABvOtb|64|48",
"Rammstein|ICH WILL|https://open.spotify.com/track/3X0K6fII7VIwL1URPrp8Ko|138|N",
"Rammstein|Sonne|https://open.spotify.com/track/3gVhsZtseYtY1fMuyYq06F|NOWOŚĆ|N",
"Rammstein|MUTTER|https://open.spotify.com/track/7jfZybgHr6yzp4iuMS2K8u|NOWOŚĆ|N",
"Reamonn|SUPERGIRL|https://open.spotify.com/track/3FhNJaCNypOAnZccdYGAWN|157|114",
"Red Hot Chili Peppers|BY THE WAY|https://open.spotify.com/track/1f2V8U1BiWaC9aJWmpOARe|142|112",
"Red Hot Chili Peppers|CALIFORNICATION|https://open.spotify.com/track/48UPSzbZjgc449aqz8bxox|9|26",
"Red Hot Chili Peppers|BLACK SUMMER|https://open.spotify.com/track/3a94TbZOxhkI9xuNwYL53b|NOWOŚĆ|N",
"Robbie Williams|SUPREME|https://open.spotify.com/track/7rQiW2mJDbP77h2RLlASTw|15|44",
"Robbie Williams|THE ROAD TO MANDALAY|https://open.spotify.com/track/2HEQUu0ydMFIp6JDvCHFzZ|135|137",
"Robert Miles|CHILDREN (DREAM VERSION)|https://open.spotify.com/track/7cEkyAXkwXCxTR3IKE0XHu|168|N",
"Royal Blood|FIGURE IT OUT|https://open.spotify.com/track/3MjrueDQKVr6xDDseZwhEd|48|N",
"Royal Blood|LITTLE MONSTER|https://open.spotify.com/track/5fpj84RsT9cOTfWUCxBTXu|95|N",
"Röyksopp|MONUMENT (THE INEVITABLE END VERSION)|https://open.spotify.com/track/3Lv59zQJQMIpZiSlszhc9T|44|N",
"Röyksopp|WHAT ELSE IS THERE?|https://open.spotify.com/track/2cTOee6bTauDFK1QuDS1BD|45|7",
"Röyksopp|HERE SHE COMES AGAIN|https://open.spotify.com/track/4ciy2AF8Q4g3ZxJVHTJ2jV|NOWOŚĆ|N",
"Röyksopp, Karen Harding|UNITY|https://open.spotify.com/track/0wNgwV6yNvYQyQMsdy3Kww|NOWOŚĆ|N",
"Sabaton|UPRISING|https://open.spotify.com/track/0cajnv3diwVnb2KXv7hLVs|215|16",
"Sheryl Crow|TOMORROW NEVER DIES|https://open.spotify.com/track/5BOlnp7K5GMzoiKdmSJBRu|184|N",
"Skunk Anansie|CHARLIE BIG POTATO|https://open.spotify.com/track/7Bf0RPsldDH7jVi9H3wODv|NOWOŚĆ|N",
"Slipknot|SNUFF|https://open.spotify.com/track/3RptaQ5Xb8WvtpItZ2f9Hi|NOWOŚĆ|N",
"Smashing Pumpkins|BULLET WITH BUTTERFLY WINGS|https://open.spotify.com/track/6GtX0jaNL8IjVQfrDBx81z|NOWOŚĆ|N",
"Sneaker Pimps|LOW FIVE|https://open.spotify.com/track/6laFEOBKHKBQLq9cso76Rp|212|N",
"Soundgarden|BLACK HOLE SUN|https://open.spotify.com/track/2EoOZnxNgtmZaD8uUmz2nD|106|-41",
"Stereophonics|GRAFFITI ON THE TRAIN|https://open.spotify.com/track/3qGl6bfdUNjgDG3fvHZVAu|38|188",
"Stereophonics|MAYBE TOMORROW|https://open.spotify.com/track/6SXy02aTZU3ysoGUixYCz0|127|121",
"Steve Hackett|IN MEMORIAM|https://open.spotify.com/track/5jHXV9RBAYs3E3PhMcStfV|128|149",
"Sting|A THOUSAND YEARS|https://open.spotify.com/track/5uLEHBpOuP5YWQPuzGpPwG|189|89",
"Sting|FIELDS OF GOLD|https://open.spotify.com/track/0I1DJdLt9BKOb7GWmWxCjo|93|225",
"Sting|SHAPE OF MY HEART|https://open.spotify.com/track/6CKoWCWAqEVWVjpeoJXyNH|19|0",
"Sting, Cheb Mami|DESERT ROSE|https://open.spotify.com/track/3zYufmyv6HOuiHn1eMR6Ja|NOWOŚĆ|N",
"Supergrass|ALRIGHT|https://open.spotify.com/track/5CQvKyzkWI7TnUu2oB9QZ0|146|N",
"Susanne Sundfør|THE BROTHEL|https://open.spotify.com/track/51MQVOb8eaovWvG16KedgA|181|N",
"System Of A Down|CHOP SUEY!|https://open.spotify.com/track/2DlHlPMa4M17kufBvI2lEN|18|-8",
"Tame Impala|LET IT HAPPEN|https://open.spotify.com/track/2X485T9Z5Ly0xyaghN73ed|91|N",
"Tame Impala|THE LESS I KNOW THE BETTER|https://open.spotify.com/track/6K4t31amVTZDgR3sKmwUJJ|NOWOŚĆ|N",
"Them Crooked Vultures|SPINNING IN DAFFODILS|https://open.spotify.com/track/4EN9GOVMjMrCFbkFD8swf4|NOWOŚĆ|N",
"Tool|SCHISM|https://open.spotify.com/track/55mJleti2WfWEFNFcBduhc|14|2",
"Tool|THE POT|https://open.spotify.com/track/1lATXTBJDHwawvT1UfxWu3|131|N",
"Tool|PNEUMA|https://open.spotify.com/track/03sEzk1VyrUZSgyhoQR0LZ|NOWOŚĆ|N",
"Toploader|DANCING IN THE MOONLIGHT|https://open.spotify.com/track/3Fzlg5r1IjhLk2qRw667od|NOWOŚĆ|N",
"Travis|SING|https://open.spotify.com/track/4yA2SM7XCLkSgkBUSoZb5S|143|120",
"Travis|WHY DOES IT ALWAYS RAIN ON ME?|https://open.spotify.com/track/5MmWgG5KgiqSxkOZdVXRQA|213|N",
"Type O Negative|WHITE SLAVERY|https://open.spotify.com/track/1MksROV8M2AvosxFAAPksF|145|N",
"Type O Negative|EVERYTHING DIES|https://open.spotify.com/track/708b4yGsLuBrHlrm1zZQBJ|NOWOŚĆ|N",
"Type O Negative|WOLF MOON (INCLUDING ZOANTHROPIC PARANOIA)|https://open.spotify.com/track/1Yb9Nq9PTEegiOUGwyGHuP|NOWOŚĆ|N",
"U2|BEAUTIFUL DAY|https://open.spotify.com/track/0gzqZ9d1jIKo9psEIthwXe|55|218",
"U2|HOLD ME, THRILL ME, KISS ME, KILL ME|https://open.spotify.com/track/5TsHqbDKaSs4ECZX0045YS|169|N",
"U2|MOMENT OF SURRENDER|https://open.spotify.com/track/2PwwiKJYMYbuWh7j5yAbwT|NOWOŚĆ|N",
"The Verve|BITTER SWEET SYMPHONY|https://open.spotify.com/track/57iDDD9N9tTWe75x6qhStw|84|50",
"The Weeknd|BLINDING LIGHTS|https://open.spotify.com/track/0VjIjW4GlUZAMYd2vXMi3b|NOWOŚĆ|N",
"The White Stripes|SEVEN NATION ARMY|https://open.spotify.com/track/3dPQuX8Gs42Y7b454ybpMR|4|5",
"Wolfsheim|KEIN ZURÜCK|https://open.spotify.com/track/5NGsvd9Wf6fzu3Dux4DQAu|159|N",
"Yppah|R. MULLEN|https://open.spotify.com/track/3yHXhzK24908z2WMW0rivQ|NOWOŚĆ|N",
"Zaz|SI JAMAIS J'OUBLIE (LIVE 2015)|https://open.spotify.com/track/1KkPVmfNmNND1vm5PhUv5R|100|N",
]
