SongsSRC = [
'1988 feat. Szczyl, Asthma, Dj Zeten|PRZYPŁYW|',
'Abradab|POWIETRZE|',
'Adam Bałdych|LOVE|',
'Adam Bałdych|POETRY|',
'Afro Kolektyw|PARANOJA NA BLOKU|',
'Afro Kolektyw|TRENER SZEWCZYK|',
'Aga Zaryan|MIŁOŚĆ|',
'Aga Zaryan i Grzegorz Turnau|TO JEDNO|',
'Agata Karczewska|FOOL|',
'Akurat|DO PROSTEGO CZŁOWIEKA|',
'Akurat|LUBIĘ MÓWIĆ Z TOBĄ|',
'Akurat|TYLKO NAJWIĘKSI|',
'Albo Inaczej feat. Muniek Staszczyk|CO TO ZA MIEJSCE?|',
'Andy|NIC Z TEGO NIE BĘDZIE|',
'Ania Dąbrowska|BAWIĘ SIĘ ŚWIETNIE|',
'Ania Dąbrowska|CHARLIE, CHARLIE|',
'Ania Dąbrowska|CZEKAM|',
'Ania Dąbrowska|NIEPRAWDA|',
'Ania Dąbrowska|NIGDY WIĘCEJ NIE TAŃCZ ZE MNĄ|',
'Ania Dąbrowska|TEGO CHCIAŁAM|',
'Ania Dąbrowska|TRUDNO MI SIĘ PRZYZNAĆ|',
'Ania Dąbrowska|W SPODNIACH CZY W SUKIENCE|',
'Ania Rusowicz|CZY DA SIĘ KOCHAĆ|',
'Ania Rusowicz|DO LASU|',
'Ania Rusowicz|JA I TY|',
'Ania Rusowicz|PTAKI|',
'Ania Rusowicz|ŚLEPA MIŁOŚĆ|',
'Ania Rusowicz|ŚWIECIE STÓJ|',
'Ania Rusowicz|TO NIE JA|',
'Ania Rusowicz i Mitch i Mitch|W CO MAM UWIERZYĆ|',
'Anieli|JAŚNIEJĄCA|',
'Anieli|NIEMIŁOŚĆ|',
'Arek Kłusowski|ANTARKTYDA|',
'Arek Kłusowski|IDEALNY SYN|',
'Artur Andrus|BABA NA PSY|',
'Artur Andrus|CIESZYŃSKA|',
'Artur Andrus|CZARNA HELENA PO ROKU|',
'Artur Andrus|NAZYWALI GO MARYNARZ|',
'Artur Andrus|NIE ZACZYNAJ|',
'Artur Andrus|OD JOKOHAMY DO FUJISAWY|',
'Artur Andrus|PIŁEM W SPALE, SPAŁEM W PILE|',
'Artur Andrus|STARGARD IN THE NIGHT|',
'Artur Andrus i Dorota Miśkiewicz|BAMBINO JAZZU|',
'Artur Andrus i Dorota Miśkiewicz|CIOCIA W GABLOCIE|',
'Artur Andrus i Monika Borzym|ZUPA NIC|',
'Artur Rojek|BEKSA|',
'Artur Rojek|BEZ KOŃCA|',
'Artur Rojek|CISZA I WIATR|',
'Artur Rojek|CZAS, KTÓRY POZOSTAŁ|',
'Artur Rojek|KUNDEL|',
'Artur Rojek|SPORTOWE ŻYCIE|',
'Artur Rojek|SYRENY|',
'Artur Rojek|W DRODZE|',
'Artur Rojek|WSZYSTKO MI MÓWI, ŻE MNIE KTOŚ POKOCHAŁ|',
'ATLVNTA|UMRZESZ TAK JAK JA|',
'Baasch|CORRIDORS|',
'Baasch|KIND OF COMA|',
'Baasch|MIASTO|',
'BAiKA|JEŚLI TYLKO TO BĘDZIE MOŻLIWE|',
'Ballady i Romanse|KTO PRZEPŁYNIE|',
'Ballady i Romanse|PRZYSZŁAM DO MIASTA|',
'Baranovski|CZUŁE MIEJSCE|',
'Barbara Wrońska|DOM Z OGNIA I LODU|',
'Barbara Wrońska|NIE CZEKAJ|',
'Barbara Wrońska|NIEUSTRASZENI|',
'Barbara Wrońska|SERCE|',
'Bartas Szymoniak|WOJOWNIK Z MIŁOŚCI|',
'Bass Astral x Igo|FEELING EXACTLY|',
'Bass Astral x Igo|JUNO|',
'Bass Astral x Igo|ORELL|',
'Bedoes|1986|',
'Bedoes|1998 (MAM TO WE KRWI)|',
'Bedoes|BEDOESIARA|',
'Bedoes feat. Taco Hemingway|CHŁOPAKI NIE PŁACZĄ|',
'Bisquit|PROSTA HISTORIA|',
'Bisquit|WIELKI MAŁY CZŁOWIEK|',
'Bisz|BANICJA|',
'Bisz/Radex|NIE OBRAŻAJ SIĘ|',
'Bitamina|DOM|',
'Bitamina|NIECH NO TYLKO ZAKWITNĄ JABŁONIE|',
'Blindead|MY NEW PLAYGROUND BECAME|',
'Blindead|NIEPOWODZENIE|',
'Blindead|S1|',
'Blurred Pink|CZY TU JEST NASZ DOM?|',
'Bluszcz|GEPARD|',
'Bluszcz|LAMPARTY|',
'Bluszcz|LASY PRYWATNE|',
'Bluszcz|LATA DWUDZIESTE|',
'Bluszcz|ODRA|',
'Bluszcz|SIMSON|',
'Błoto|PROSTACTWO|',
'Bokka|900|',
'Bokka|TOWN OF STRANGERS|',
'Bokka|VIOLET MOUNTAIN TOPS|',
'Borixon|TRWAM W TYM|',
'Bovska|DZIKA|',
'Bovska|KAKTUS|',
'Bovska|WUJEK G.|',
'Braty Z Rakemna|FALBANKI|',
'Brodka|DZIEWCZYNA MOJEGO CHŁOPAKA|',
'Brodka|GAME CHANGE|',
'Brodka|GRANDA|',
'Brodka|HORSES|',
'Brodka|MIAŁEŚ BYĆ|',
'Brodka|MY NAME IS YOUTH|',
'Brodka|SADZA|',
'Brodka|TEN|',
'Brodka|UP IN THE HILL|',
'Brodka|VARSOVIE|',
'Brodka|W PIĘCIU SMAKACH|',
'Brodka|ZNAM CIĘ NA PAMIĘĆ|',
'Brodka i A_GIM|WSZYSTKO CZEGO DZIŚ CHCĘ|',
'Bruno Schulz|LAURA|',
'Budyń|DŻEZ|',
'Buldog|PIĄTY ROZBIÓR POLSKI|',
'Buldog|PIOSENKA O BOŚNI|',
'Buslav|SEARCHING FOR YOU|',
'Cała Góra Barwinków|24 GODZINY|',
'Chemia|SEND ME THE RAVENS|',
'Chłopcy kontra Basia|OJ TAK!|',
'Clock Machine|MORPHINE|',
'Coals|SUGAR|',
'Coals|UFO|',
'Coma|CISZA I OGIEŃ|',
'Coma|DALEKA DROGA DO DOMU|',
'Coma|FANTAZJA|',
'Coma|LAJKI|',
'Coma|LESZEK ŻUKOWSKI|',
'Coma|LOS, CEBULA I KROKODYLE ŁZY|',
'Coma|ODWOŁANE|',
'Coma|PROSTE DECYZJE|',
'Coma|SPADAM|',
'Coma|STO TYSIĘCY JEDNAKOWYCH MIAST|',
'Coma|SYSTEM|',
'Coma|TONACJA (SYGNAŁ Z PIEKŁA)|',
'Coma|WĘDRÓWKA|',
'Coma|WOLA ISTNIENIA|',
'Coma|ZAPRZEPASZCZONE SIŁY WIELKIEJ ARMII ŚWIĘTYCH ZNAKÓW|',
'Coma feat. Ralph Kaminski|POŻEGNANIE Z BAJKĄ|',
'Cool Kids Of Death|BUTELKI Z BENZYNĄ I KAMIENIE|',
'Cool Kids Of Death|GENERACJA NIC|',
'Cool Kids Of Death|KRĘCIMY SIĘ W KÓŁKO|',
'Cool Kids Of Death|NAGLE ZAPOMNIEĆ WSZYSTKO|',
'Cool Kids Of Death|UWAŻAJ|',
'Cuba De Zoo|CZARNE AUTO|',
'Cuba De Zoo|GRÓB|',
'Curly Heads|BURNING DOWN|',
'Curly Heads|DIADRE|',
'Curly Heads|M.A.B.|',
'Curly Heads|RECONCILE|',
'Curly Heads|SYNTHLOVE|',
'Czesław Mozil i Hania Rani|Z MIŁOŚCI|',
'Czesław Mozil i Grajkowie Przyszłości|NIE MA CZASU|',
'Czesław Śpiewa|MASZYNKA DO ŚWIERKANIA|',
'Czesław Śpiewa|MIESZKO I DOBRAWA JAKO POCZĄTEK PAŃSTWA POLSKIEGO|',
'Czesław Śpiewa|W SAM RAZ|',
'Czesław Śpiewa i Mela Koteluk|PIEŚŃ O SZCZĘŚCIU|',
'Dagadana|GOI TY NASZA PANI|',
'Dagadana|TANGO|',
'Daniel Bloom i Mela Koteluk|KATARAKTA|',
'Daniel Bloom i Tomek Makowiecki|HEARTBREAKERS|',
'Daria Zawiałow|GDYBYM MIAŁA SERCE|',
'Daria Zawiałow|HEJ HEJ!|',
'Daria Zawiałow|HELSINKI|',
'Daria Zawiałow|JESZCZE W ZIELONE GRAMY|',
'Daria Zawiałow|KAONASHI|',
'Daria Zawiałow|KUNDEL BURY|',
'Daria Zawiałow|MALINOWY CHRUŚNIAK|',
'Daria Zawiałow|METROPOLIS|',
'Daria Zawiałow|NIE DOBIJĘ SIĘ DO CIEBIE|',
'Daria Zawiałow|PUNK FU!|',
'Daria Zawiałow|SZARÓWKA|',
'Daria Zawiałow|WOJNY I NOCE|',
'Daria Zawiałow|ŻÓŁTA TAKSÓWKA|',
'Daria Zawiałow i Dawid Podsiadło|ZA KRÓTKI SEN|',
'Daria Zawiałow feat. Szafter i Ralph Kaminski|CZY TY SŁYSZYSZ MNIE?|',
'Dawid Podsiadło|0,1875|',
'Dawid Podsiadło|MAŁOMIASTECZKOWY|',
'Dawid Podsiadło|NAJNOWSZY KLIP|',
'Dawid Podsiadło|NIE MA FAL|',
'Dawid Podsiadło|NIEZNAJOMY|',
'Dawid Podsiadło|PASTEMPOMAT|',
'Dawid Podsiadło|POST|',
'Dawid Podsiadło|POWIEDZ MI, ŻE NIE CHCESZ|',
'Dawid Podsiadło|TROFEA|',
'Dawid Podsiadło|TRÓJKĄTY I KWADRATY|',
'Dawid Podsiadło|W DOBRĄ STRONĘ|',
'Dawid Podsiadło|WHERE DID YOUR LOVE GO?|',
'Dawid Tyszkowski|KOSZULKA|',
'Dick4Dick|DICK BACK IN TOWN|',
'Dick4Dick|HOLLYWOOD|',
'Dominik Wania|LIQUID FLUID|',
'Dominik Wania|NEW LIFE EXPERIENCE|',
'Dominik Wania|THINK TWICE|',
'Domowe Melodie|GRAŻKA|',
'Donguralesko|BETONOWE LASY MOKNĄ|',
'Donguralesko|CHCĘ CI DAĆ|',
'Donguralesko|EL POLAKO|',
'Dorota Miśkiewicz|POZA CZASEM|',
'Dorota Osińska|CZEŚĆ TO JA|',
'Dr Misio|PISMO|',
'Dubska|AVOKADO|',
'The Dumplings|KOCHAM BYĆ Z TOBĄ|',
'The Dumplings|NIE GOTUJEMY|',
'The Dumplings|PRZYKRO MI|',
'The Dumplings|RAJ|',
'The Dumplings|TECHNICOLOR YAWN|',
'Dwa Sławy|A MOŻE BY TAK?|',
'Dwa Sławy|O SPORTOWCU, KTÓREMU NIE WYSZŁO|',
'Dylan.pl i Muniek Staszczyk|CZASY NADCHODZĄ NOWE|',
'EABS|GLOBAL WARMING|',
'EABS|LUCIFER (A NEW SUN)|',
'EABS|NIEKOCHANA|',
'EABS|POŁUDNICA|',
'EABS|UFO|',
'Eis|NAJLEPSZE DNI|',
'Eldo|CHODŹ ZE MNĄ|',
'Eldo|GRANICE|',
'Eldo|NIE PYTAJ O NIĄ|',
'Em|KILKA WYJŚĆ|',
'Em|TRAMWAJE JAK KOMETY|',
'Evorevo|DWUBIEGUNOWA|',
'Ewelina Flinta|NIE ZNASZ MNIE|',
'Fertile Hump|KISS KISS BANG BANG|',
'Fertile Hump|SAILOR’S GRAVE|',
'Fismoll|LET’S PLAY BIRDS|',
'Fismoll|NA CO CI TO|',
'Fismoll|TRIFLE|',
'Fisz Emade Tworzywo|BIEGNIJ DALEJ SAM|',
'Fisz Emade Tworzywo|DWA OGNIE|',
'Fisz Emade Tworzywo|FANATYCY|',
'Fisz Emade Tworzywo|JESTEM W NIEBIE|',
'Fisz Emade Tworzywo|KANTERSTRAJK|',
'Fisz Emade Tworzywo|OK BOOMER|',
'Fisz Emade Tworzywo|SPEKTRUM BARW|',
'Fisz Emade Tworzywo|TELEFON|',
'Fisz Emade Tworzywo|WOJNA|',
'Fisz Emade Tworzywo|WOLNE DNI|',
'Fisz Emade Tworzywo|ZA MAŁO CZASU|',
'Fisz Emade Tworzywo|ZWIEDZAM ŚWIAT|',
'Fisz Emade Tworzywo|ZWYKŁY|',
'Fisz Emade Tworzywo feat. Chilly Gonzales, Justyna Święs|ŚLADY|',
'Fisz Emade Tworzywo feat. Justyna Święs|PYŁ|',
'Franio Mucha|MIŚ MAMONA|',
'Furia|OPĘTANIEC|',
'Furia|SĄ TO KOŁA|',
'Furia|ZA ĆMĄ, W DYM|',
'Furia|ZWYKŁE CZARY WIEJĄ|',
'Futro|WYSPY|',
'Gaba Kulka|KARA NINY|',
'Gaba Kulka|NIEJASNOŚCI|',
'Gaba Kulka|WIELKIE WRAŻENIE|',
'Gaba Kulka i Warszawska Orkiestra Rozrywkowa|MIŁOŚĆ JEST JAK NIEDZIELA|',
'GrubSon|NA SZCZYCIE|',
'Gruzja|KRÓLOWIE ZWIERZĄT|',
'Gruzja|MANAM|',
'Hades|SŁOWA|',
'Hades|ZMIANY|',
'Hania Rani|EDEN|',
'Hania Rani|GLASS|',
'Hania Rani|HAWAII OSLO|',
'Happysad|JAK DAWNIEJ|',
'Happysad|ŁYDKA|',
'Happysad|MGŁA NA TORACH|',
'Happysad|MILOWY LAS|',
'Happysad|MÓW MI DOBRZE|',
'Happysad|NADZY NA MRÓZ|',
'Happysad|NOSTRESS|',
'Happysad|OD TAŃCA|',
'Happysad|WRÓCIMY TU JESZCZE|',
'Happysad|ZANIM PÓJDĘ|',
'Hatifnats|WAKING IN THE DARK|',
'Hidden By Ivy|THE RAINMAKER|',
'Husky|PIOSENKA NIENASYCONA|',
'HV/Noon feat. Eldo|WILK|',
'HV/Noon feat. Hades|EUROPA CENTRALNA|',
'Igo|BRUDAS|',
'Igo|HELENA|',
'Igor Herbut|JASNY|',
'Igor Herbut|TAŃCZMY|',
'Igor Herbut|WDZIĘCZNOŚĆ|',
'Jamal|DEFTO|',
'Jamal|PERON|',
'Jamal|POLICEMAN|',
'Jamal|SŁOŃCA ŁAN|',
'Jan-Rapowanie|PILOT|',
'Jan-Rapowanie|UKŁADANKA|',
'Janek Samołyk|PROBLEM Z WIERNOŚCIĄ|',
'Janusz Radek|DOBRO|',
'Janusz Radek|KIEDY U… KOCHANIE|',
'Janusz Radek|POCZTÓWKA Z AVIGNION|',
'Jazz Band Młynarski-Masecki|ABDUŁ BEY|',
'Jazz Band Młynarski-Masecki|HOW DO YOU DO MR. BROWN?|',
'Jazzpospolita|LASZLO AND COUSINS|',
'Jelonek|A. VIVALDI - PRESTO|',
'Jelonek|VIOLMACHINE|',
'Julia Marcell|ANDREW|',
'Julia Marcell|MAREK|',
'Julia Marcell|MATRIOSZKA|',
'Julia Marcell|PRAWDOPODOBIEŃSTWO|',
'Julia Marcell|TARANTINO|',
'Julia Marcell|TETRIS|',
'Julia Pietrucha|ON MY OWN|',
'Julia Pietrucha|SAILOR|',
'Julia Pietrucha|WE CARE SO MUCH|',
'Julia Pietrucha|WHO KNOWS|',
'Justyna Święs|CZERWONA SUKIENKA|',
'Kalina|NAWET JEŚLI|',
'Kamil Piotrowicz Sextet|TFE|',
'Kamil Pivot|MANDARYNKI|',
'Kamp!|"BREAKING A GHOSTS HEART"|',
'Kamp!|CAIRO|',
'Kamp!|DISTANCE OF THE MODERN HEARTS|',
'Kamp!|HEATS|',
'Kamp!|PLAY ME DIRTY|',
'Kanał Audytywny|RADIOWA PIOSENKA O NICZYM|',
'Kanał Audytywny|SKRZYNIA IKARUSA|',
'Karaś/Rogucki|BOLESNE STRZAŁY W SERCE|',
'Karaś/Rogucki|KATRINA|',
'Karaś/Rogucki|KILKA WESTCHNIEŃ|',
'Karaś/Rogucki|ZAPASOWY TLEN|',
'Karolina Kozak|MIMOCHODEM|',
'Kasia Lins|RÓB TAK DALEJ|',
'Kasia Lins|WIERSZ OSTATNI|',
'Kaśka Sochacka|CICHE DNI|',
'Kaśka Sochacka|NIEBO BYŁO RÓŻOWE|',
'Kaśka Sochacka|WIŚNIA|',
'Kaśka Sochacka i Kortez|DLA MNIE TO JUŻ KONIEC|',
'Kawałek Kulki|KOLEGI TATA|',
'Kawałek Kulki|WYSZLIŚMY|',
'Kękę|CESARZ|',
'Kękę|NIGDY PONAD STAN|',
'Kękę|ZROBIŁEŚ TO CHŁOPAK|',
'Kiev Office|DWUPŁATOWCE|',
'Kim Nowak|MOKRY PIES|',
'Kim Nowak|PISTOLET|',
'Kombajn Do Zbierania Kur Po Wioskach|POŁĄCZENIA|',
'Kombajn Do Zbierania Kur Po Wioskach|WARSZAWA|',
'Komety|BEZSENNE NOCE|',
'Komety|MIASTO TURYSTÓW|',
'Komety|SPOTKAJMY SIĘ POD KONIEC SIERPNIA|',
'Kortez|DOBRY MOMENT|',
'Kortez|DOBRZE, ŻE CIĘ MAM|',
'Kortez|HEJ, WY|',
'Kortez|OD DAWNA JUŻ WIEM|',
'Kortez|STARE DRZEWA|',
'Kortez|WRACAJ DO DOMU|',
'Kortez|WYJDŹ ZE MNĄ NA DESZCZ|',
'Kortez|Z IMBIREM|',
'Kortez|ZOSTAŃ|',
'Kowalski|IRLANDIA ZIELONA|',
'Kowalski|MARIAN|',
'Kroki|BALON|',
'Król|CAŁĄ CISZĘ / POKÓJ NOCNY|',
'Król|DLA ZABAWY|',
'Król|DRUGA POMOC|',
'Król|GŁODNE DUSZE|',
'Król|GŁOS WEWNĘTRZNY|',
'Król|SPRÓBUJĘ / STRAŻNIK|',
'Król|TAK JAK TY|',
'Król|TE SMAKI I ZAPACHY|',
'Król|Z TOBĄ / DO DOMU|',
'Król|ZAKLĘCIE|',
'Król|ZBYT DOBRZE CI IDZIE|',
'Krzysztof Kiljański i Kayah|PRÓĆZ CIEBIE, NIC|',
'Krzysztof Zalewski|ANNUSZKA|',
'Krzysztof Zalewski|JAK DOBRZE|',
'Krzysztof Zalewski|JAŚNIEJ|',
'Krzysztof Zalewski|JEDNEGO SERCA|',
'Krzysztof Zalewski|KURIER|',
'Krzysztof Zalewski|MIŁOŚĆ, MIŁOŚĆ|',
'Krzysztof Zalewski|OCZKO W GŁOWIE|',
'Krzysztof Zalewski|POLSKO|',
'Krzysztof Zalewski|PRZYJDŹ W TAKĄ NOC|',
'Krzysztof Zalewski|PTAKI (MTV UNPLUGGED)|',
'Krzysztof Zalewski|TYLKO NOCĄ|',
'Krzysztof Zalewski|WILK|',
'Kuba Badach|WYKIDAJŁO CZAS|',
'Kuba Kawalec|ŚLEPOTA|',
'Kuba Więcek|ANOTHER RAINDROP|',
'Kuba Więcek|MULTITASKING|',
'Kumka Olik|GRZECZNE DZIEWCZYNKI|',
'Kumka Olik|PODOBNO NIE MA JUŻ FRANCJI|',
'Kwiat Jabłoni|BUKA|',
'Kwiat Jabłoni|DZIŚ PÓŹNO PÓJDĘ SPAĆ|',
'Kwiat Jabłoni|KOMETA|',
'Kwiat Jabłoni|MOGŁO BYĆ NIC|',
'Kwiat Jabłoni|NIC WIĘCEJ|',
'Kwiat Jabłoni feat. Bum Bum Orkestar|IDZIE ZIMA|',
'L. Stadt|DEATH OF A SURFER GIRL|',
'L.Stadt|COME AWAY MELINDA|',
'L.Stadt|OCZY KAMIENIC|',
'L.Stadt|U.F.O.|',
'L.U.C. + Smolik + Orkiestra Rebel Babel|TADEUSZ|',
'L.U.C. feat. Irena Jarocka, Buka|BAŚŃ O ROZSTANIU|',
'Lachowicz|NIE MA MNIE|',
'Lao Che|CZARNE KOWBOJE|',
'Lao Che|HISZPAN|',
'Lao Che|HYDROPIEKŁOWSTĄPIENIE|',
'Lao Che|KAPITAN POLSKA|',
'Lao Che|NIE RAJ|',
'Lao Che|PRĄD STAŁY / PRĄD ZMIENNY|',
'Lao Che|SEN A’LA TREN|',
'Lao Che|SPÓŁDZIELNIA|',
'Lao Che|UNITED COLORS OF ARMAGEDON|',
'Lao Che|URODZIŁA MNIE CIOTKA|',
'Lao Che|WOJENKA|',
'LemON|NAPRAW|',
'LemON|PTAKI|',
'LemON|SCARLET|',
'Lenny Valentino|CHŁOPIEC Z PLASTELINY|',
'Lenny Valentino|DOM NAUKI WRAŻEŃ|',
'Lenny Valentino|OTTO PILOTTO|',
'Leski|CHINY|',
'Leski|LEPIEJ WCALE|',
'Leski|NIE CHCĘ ZMIENIAĆ NIC|',
'Leski|SUPERSAM|',
'Leski|ULOTNY|',
'Leski|WSZYSTKO CO KOCHAM|',
'Limboski|MATCE ZIEMI|',
'Limboski|NA STATKU|',
'Limboski|W TRAWIE|',
'Lor|NIKT|',
'Lunatic Soul|A THOUSAND SHARDS OF HEAVEN|',
'Luxtorpeda|44 DNI|',
'Luxtorpeda|AUTYSTYCZNY|',
'Luxtorpeda|MAMBAŁAGA|',
'Luxtorpeda|PRZYGOTUJ SIĘ NA NAJLEPSZE|',
'Luxtorpeda|WILKI DWA|',
'Łąki Łan|JAMMIN’|',
'Łąki Łan|POLA AR|',
'Łona i Webber|BŁĄD|',
'Łona i Webber|GDZIE TAK PIĘKNIE|',
'Łona i Webber|KALORYFER|',
'Łona i Webber|MIEJ WĄTPLIWOŚCI|',
'Łona i Webber|ROZMOWA|',
'Łona i Webber|TO NIC NIE ZNACZY|',
'Łona i Webber|WYŚLIJ SOBIE POCZTÓWKĘ|',
'Łydka Grubasa|RAPAPARA|',
'Maciej Obara Quartet|ONE FOR|',
'Maciej Obara Quartet|UNLOVED|',
'MaJLo|THE BIRD’S SONG|',
'MaJLo feat. Natalia Grosiak|ZŁOTO|',
'Makowiecki Band|MIĘDZY NOCĄ A DNIEM|',
'Małpa|MIAŁEM TO RZUCIĆ|',
'Małpa|NIE BYŁEM NIGDY|',
'Małpa|PAZNOKCIE|',
'Marcin Pater Trio|NOTHING BUT TROUBLE|',
'Marcin Przybyłowicz|WILCZA ZAMIEĆ [PIOSENKA Z GRY WIEDŹMIN 3: DZIKI GON]|',
'Marcin Rozynek|NICK OF TIME|',
'Marcin Rozynek|SIŁACZ|',
'Marcin Rozynek|ŚLEPY LOS|',
'Marcin Wasilewski Trio|DIAMONDS AND PEARLS|',
'Marcin Wasilewski Trio|GLIMMER OF HOPE|',
'Marcin Wasilewski Trio|SPARK OF LIFE|',
'Maria Peszek|LOVESONG|',
'Maria Peszek|LUDZIE PSY|',
'Maria Peszek|MIŁY MÓJ|',
'Maria Peszek|MOJE MIASTO|',
'Maria Peszek|MUCHOMORY|',
'Maria Peszek|NIE MAM CZASU NA SEKS|',
'Maria Peszek|ROSÓŁ|',
'Maria Peszek|SORRY POLSKO|',
'Marika|SIŁA OGNIA|',
'Marika feat. Gooral|A JEŚLI TO JA|',
'Mary Komasa|COME|',
'Mata|KISS CAM|',
'Mata|PATOINTELIGENCJA|',
'Mazolewski/Porter|DON’T ASK ME QUESTIONS|',
'Mazolewski/Porter|MELANCHOLIA|',
'Mazolewski/Porter|STRANGER|',
'Me and That Man|CYRULIK JACK / MY CHURCH IS BLACK|',
'Meek, Oh Why?|NOCNE NIEBO|',
'Mela Koteluk|DZIAŁAĆ BEZ DZIAŁANIA|',
'Mela Koteluk|FASTRYGI|',
'Mela Koteluk|HEN, HEN|',
'Mela Koteluk|MELODIA ULOTNA|',
'Mela Koteluk|ODPROWADŹ|',
'Mela Koteluk|OGNIWO|',
'Mela Koteluk|WIELKIE NIEBA|',
'Mela Koteluk|WOLNA|',
'Mela Koteluk|ŻURAWIE ORIGAMI|',
'Mela Koteluk i Kwadrofonik|ASTRONOMIA|',
'Mery Spolsky|MIŁO BYŁO PANA POZNAĆ|',
'Męskie Granie 2010: Wojciech Waglewski, Maciej Maleńczuk i Abradab|WSZYSCY MUZYCY TO WOJOWNICY|',
'Męskie Granie 2011: Wojciech Waglewski, Lech Janerka, Spięty, Fisz i Leszek Możdżer|KOBIETY NAM WYBACZĄ|',
'Męskie Granie 2012: Nosowska i Marek Dyjak|OGNIA!|',
'Męskie Granie 2013: Nosowska i O.S.T.R.|JUTRO JEST DZIŚ|',
'MGO 2014: Brodka, Olaf Deriglasoff, Emade, Dawid Podsiadło i Andrzej Smolik|ELEKTRYCZNY|',
'MGO 2015: Fisz, Mela Koteluk i Andrzej Smolik|ARMATY|',
'MGO 2016: Tomasz Organek, O.S.T.R. i Dawid Podsiadło|WATAHA|',
'MGO 2017: Brodka, Tomasz Organek i Piotr Rogucki|NIEBOSKŁON|',
'MGO 2018: Dawid Podsiadło, Kortez, Krzysztof Zalewski|POCZĄTEK|',
'MGO 2019: Nosowska, Igo, Tomasz Organek i Krzysztof Zalewski|SOBIE I WAM|',
'MGO 2020: Daria Zawiałow, Król i Igo|ŚWIT|',
'MGO 2021: Daria Zawiałow, Dawid Podsiadło i Vito Bambino|I CIEBIE TEŻ, BARDZO|',
'MGO 2022: Bedoes, Krzysztof Zalewski i Kwiat Jabłoni|JEST TYLKO TERAZ|',
'Mgła|AGE OF EXCUSE IV|',
'Mgła|EXERCISES IN FUTILITY V|',
'Mika Urbaniak|IN MY DREAMS|',
'Mika Urbaniak|LOVIN’ NEEDS A DEADLINE|',
'Mikromusic|DOBRZE JEST|',
'Mikromusic|NA KRZYWY RYJ|',
'Mikromusic|SYNU|',
'Mikromusic|TAK MI SIĘ NIE CHCE|',
'Mikromusic|TAK TĘSKNIĘ|',
'Mikromusic|TAKIEGO CHŁOPAKA|',
'Miosh i Zespół Pieśni i Tańca Śląsk i Król|WOŁANIE|',
'Misia Furtak|MÓZG|',
'Mitch i Mitch|NA NA NA NA NA|',
'Mitch i Mitch|OH YEAH|',
'Miuosh i Nosowska|TRAMWAJE I GWIAZDY|',
'Miuosh | NOSPR | Smolik feat. Rogucki|WIZJE|',
'Miuosh, Nosowska|KLUCZE|',
'Młynarski-Masecki Jazz Camerata Varsoviensis|POLOWANIE NA TYGRYSA|',
'Młynek kawowy|MŁYNEK KAWOWY|',
'Monika Borzym|TY TU, JA TAM TANGO|',
'Mortas|DOM|',
'Mortas|PRZEDOSTATNI|',
'Mortas|ZA TYSIĄC LAT|',
'Możdżer Danielsson Fresco|AFRICA|',
'Możdżer Danielsson Fresco|ASTA|',
'Możdżer Danielsson Fresco|EASY MONEY|',
'Możdżer Danielsson Fresco|INCOGNITOR|',
'Możdżer Danielsson Fresco|POLSKA|',
'Mrozu|AURA|',
'Mrozu|GALACTICOS|',
'Mrozu|SZEROKIE WODY|',
'Mrozu|ZŁOTO|',
'Muchy|21 DNI|',
'Muchy|GALANTERIA|',
'Muchy|MIASTO DOZNAŃ|',
'Muchy|NIE PRZESZKADZAJ MI, BO TAŃCZĘ|',
'Muchy|NIE TAK|',
'Muchy|PRZESILENIE|',
'Muchy|SZARORÓŻOWE|',
'Muchy|ZIMNE KRAJE|',
'Muniek Staszczyk|OŁÓW|',
'Muniek Staszczyk|POLA|',
'Muzyka Końca Lata|DOKĄD|',
'Muzyka Końca Lata|EKSTRAMOCNE|',
'Muzyka Końca Lata|PRYWATNY CIECHOCINEK|',
'Natalia Przybysz|CIEPŁY WIATR|',
'Natalia Przybysz|DZIECI MALARZY|',
'Natalia Przybysz|MAYBE|',
'Natalia Przybysz|MIÓD|',
'Natalia Przybysz|NAZYWAM SIĘ NIEBO|',
'Natalia Przybysz|NIEBIESKI|',
'Natalia Przybysz|OGIEŃ|',
'Natalia Przybysz|ZEW|',
'Negatyw|AMSTERDAM|',
'Negatyw|LUBIĘ WAS|',
'Nocny Kochanek|KOŃ NA BIAŁYM RYCERZU|',
'Nosowska, Grabaż, Rojek|PROSTA RZECZ|',
'Novika|MISS MOOD|',
'O.S.T.R.|ALCATRAZ|',
'O.S.T.R.|KOCHANA POLSKO|',
'O.S.T.R.|MÓWIŁAŚ MI|',
'O.S.T.R.|POLSKA SIŁA|',
'O.S.T.R.|ŚPIJ SPOKOJNIE|',
'O.S.T.R.|TABASKO|',
'OBRASQI|DOPOWIEDZENIA|',
'Obscure Sphinx|LUNAR CAUSTIC|',
'Obscure Sphinx|NOTHING LEFT|',
'OIO|AMERYKAŃSKIE TELEDYSKI|',
'OIO|PRZYPADKIEM|',
'Organek|CAŁY TEN FEJM|',
'Organek|CZARNA MADONNA|',
'Organek|FOTOGRAF BROK|',
'Organek|GŁUPI JA|',
'Organek|ITALIANO|',
'Organek|MISSISIPI W OGNIU|',
'Organek|NIEMIŁOŚĆ|',
'Organek|O, MATKO!|',
'Organek|SAMOLOTY|',
'Organek|ULTIMO|',
'Organek|WALCZ|',
'Organek|WIOSNA|',
'Organek feat. Klaudia Szafrańska|IDZIEMY W MIASTO|',
'Otsochodzi|BON VOYAGE|',
'Otsochodzi feat. Taco Hemingway|NOWY KOLOR|',
'Pablopavo i Ludziki|BLASK|',
'Pablopavo i Ludziki|DANCINGOWA PIOSENKA MIŁOSNA|',
'Pablopavo i Ludziki|DO STU|',
'Pablopavo i Ludziki|KARWOSKI|',
'Pablopavo i Ludziki|OSTATNI DZIEŃ SIERPNIA|',
'Pablopavo i Ludziki|PANIE INŻYNIERZE|',
'Pablopavo i Ludziki|PROWADZIMY CZYNNOŚCI|',
'Pablopavo i Ludziki|ŚWIATŁA NA STATKU|',
'Pablopavo i Ludziki|TELEHON|',
'Pablopavo Iwanek Praczas|PAŹDZIERNIKOWY FACET|',
'Paluch|BEZ STRACHU|',
'Paluch|W MOIM ŻYCIU|',
'Patrick The Pan|NIE CHCĘ PSA|',
'Patrick The Pan feat. Dawid Podsiadło|NIEDOPOWIEŚCI|',
'Patrick The Pan feat. Ralph Kaminski|IMIONA TAJFUNÓW|',
'Patryk Pietrzak|TOTO|',
'Patryk Pietrzak feat. Wiktoria Boruś|MARYŚ|',
'Paula i Karol|CALLING|',
'Paulina Przybysz|PIRX|',
'Paweł Domagała|DZIECI U DZIADKÓW|',
'Paweł Domagała|WEŹ NIE PYTAJ|',
'Paweł Domagała|WYSTARCZĘ JA|',
'Pezet|CO MAM POWIEDZIEĆ|',
'Pezet|GDYBY NIE MIAŁO BYĆ JUTRA|',
'Pezet/Noon|UKRYTY W MIEŚCIE KRZYK|',
'Pianohooligan|PRELUDE NO 3 IN C SHARP|',
'Pink Freud|KONICHIWA|',
'Piotr Rogucki|PIOSENKA PISANA NOCĄ|',
'Piotr Zioła|BŁYSK|',
'Piotr Zioła|PODOBNY|',
'Piotr Zioła|SAFARI|',
'Piotr Zioła|W CIEMNO|',
'Plastic|I WANT U|',
'Plastic|LAZY DAY|',
'Pola Rise|BLACKSTAR|',
'Polskie Znaki feat. Vito Bambino|NIECH MONARCHOWIE|',
'Power of Trinity|CHODŹ ZE MNĄ|',
'Power of Trinity|PONIEDZIAŁEK|',
'Power of Trinity|SUMA RAN|',
'Pro8l3m|GROUND ZERO|',
'Pro8l3m|INTERPOL|',
'Pro8l3m|PRZEBÓJ NOCY|',
'Pro8l3m|SKRABLE|',
'Pro8l3m|STÓWA|',
'Pro8l3m|W DOMACH Z BETONU|',
'Projekt Warszawiak|NIE MA CWANIAKA NAD WARSZAWIAKA|',
'Psychocukier|SONIC CAVE|',
'Pustki|LUGOLA|',
'Pustki|NIC DO POWIEDZENIA|',
'Pustki|O KROK|',
'Pustki|PARZYDEŁKO|',
'Pustki|SIĘ WYDAWAŁO|',
'Pustki|SŁABOŚĆ CHWILOWA|',
'Pustki|TCHU MI BRAK|',
'Pustki|TELEFON DO PRZYJACIELA|',
'Pustki|TYLE Z ŻYCIA|',
'Pustki|WIERSZ O SZUKANIU|',
'Quebonafide|QUEBONAHOMBRE|',
'Quebonafide|REFREN TROCHĘ JAK LANA DEL RAY|',
'Quebonafide feat Daria Zawiałow|BUBLETEA|',
'R.U.T.A.|KTO U PANA NIE SŁUŻYŁ, BIEDY JESZCZE NIE UŻYŁ|',
'R.U.T.A.|LAMENT CHŁOPSKI|',
'Ralph Kaminski|BAL U RAFAŁA|',
'Ralph Kaminski|DUCHY|',
'Ralph Kaminski|KOSMICZNE ENERGIE|',
'Ralph Kaminski|MORZE|',
'Ralph Kaminski|PIĘĆ MINUT ŁEZ|',
'Ralph Kaminski|TATA|',
'Ralph Kaminski|WSZYSTKIEGO NAJLEPSZEGO|',
'Rasmentalism|FAST FOOD|',
'Rasmentalism|KRAJOBRAZY|',
'Rasmentalism|TRYB SAMOLOTOWY|',
'Rasmentalism feat Jan-Rapowanie|MUCHA|',
'Renton|HEY GIRL|',
'RGG|MONACHIUM|',
'RGG|STRAIGHT STORY|',
'Riverside|CONCEIVING YOU|',
'Riverside|GUARDIAN ANGEL|',
'Riverside|LOOSE HEART|',
'Riverside|RIVER DOWN BELOW|',
'Riverside|STORY OF MY DREAM|',
'Riverside|STUCK BETWEEN|',
'Riverside|THE DEPTH OF SELF-DELUSION|',
'Riverside|TIME TRAVELLERS|',
'Riverside|WE GOT USED TO US|',
'Rosalie.|NIE MÓW|',
'Rosalie.|SO GOOD|',
'Rotofobia|10 PIĘTRO|',
'Rysy feat. Justyna Święs, Piotr Zioła|PRZYJMIJ BRAK|',
'Sanah|ETC|',
'Sanah|KOLOŃSKA I SZLUGI|',
'Sanah|MELODIA|',
'Sanah|SZAMPAN|',
'Sanah i Daria Zawiałow|ELDORADO|',
'Sanah i Grzegorz Turnau|SEN WE ŚNIE|',
'Sanah i Kwiat Jabłoni|SZARY ŚWIAT|',
'Sanah feat. Vito Bambino|ALE JAZZ|',
'schafter|HOT COFFEE|',
'schafter feat. Taco Hemingway|BIGOS|',
'Sidney Polak|BYŁEM TAM|',
'Sidney Polak|CHOMICZÓWKA|',
'Sidney Polak|CHORWAT|',
'Sidney Polak|OTWIERAM WINO|',
'Sistars|INSPIRATIONS|',
'Sistars|MY MUSIC|',
'Sistars|NA DWA|',
'Sistars|SKĄD JA CIĘ MAM|',
'Sistars|SUTRA|',
'Skalpel|ESCAPE (HANIA RANI REMIX)|',
'Skalpel|SCULPTURE|',
'Skalpel|TEST DRIVE|',
'Skalpel|TOGETHER|',
'Skubas|DOBRA CZARODZIEJKA|',
'Skubas|LINOSKOCZEK|',
'Skubas|NIE MAM DLA CIEBIE MIŁOŚCI|',
'Skubas|NIE PYTAJ|',
'Small Mechanics|GĘSTNIEJĄ JESIENIE|',
'Smolik i Artur Rojek|50 TYSIĘCY 881|',
'Smolik i Kev Fox|ON THE QUIET|',
'Smolik i Kev Fox|RUN|',
'Smolik i Mika|WHO TOLD YOU?|',
'Smolik i Novika|T.TIME|',
'Smolik feat Kasia Kurzawska|CYE|',
'Snowman|NIEZMIENNIE|',
'Sobel|FIOŁKOWE POLE|',
'Sofa|ONA MOVIE|',
'Sokół|CHCEMY BYĆ WYŻEJ|',
'Sokół|KAŻDY PONAD KAŻDYM|',
'Sokół feat. Fasolki|JAK UROSNĘ|',
'Sonbird|WODOSPADY|',
'Sorry Boys|ABSOLUTNIE, ABSOLUTNIE|',
'Sorry Boys|JADĘ DO DOMU|',
'Sorry Boys|MIŁOŚĆ|',
'Sorry Boys|WARSZAWA CZEKA|',
'Sorry Boys|WRACAM|',
'Sorry Boys|ZWYCZAJNE CUDA|',
'Sosnowski|DALEJ|',
'Sosnowski|DESZCZ|',
'Sosnowski|PYŁ|',
'Spięty|MA CZAR KARMA|',
'Spięty|TRYBUNA MAŁPOLUDU|',
'Stanisława Celińska|CUDEM JEST ŚWIAT|',
'Stanisława Celińska|CZERŃ I BIEL|',
'Stanisława Celińska|TRUDNY DZIEŃ|',
'Stanisława Celińska i Muniek Staszczyk|WIELKA SŁOTA|',
'Strachy Na Lachy|BTW|',
'Strachy Na Lachy|CHORY NA WSZYSTKO|',
'Strachy Na Lachy|CO SIĘ Z NAMI STAŁO|',
'Strachy Na Lachy|DZIEŃ DOBRY, KOCHAM CIĘ|',
'Strachy Na Lachy|I CAN’T GET NO GRATISFACTION|',
'Strachy Na Lachy|JEDNA TAKA SZANSA NA STO|',
'Strachy Na Lachy|KATASTROFA SZCZĘŚCIA|',
'Strachy Na Lachy|MORALNE SALTO|',
'Strachy Na Lachy|PIŁA TANGO|',
'Strachy Na Lachy|PO PROSTU PASTELOWE|',
'Strachy Na Lachy|WALKA JAKUBA Z ANIOŁEM|',
'Strachy Na Lachy|ZACHMURZONY W TOBIE|',
'Strachy Na Lachy|ŻYJĘ W KRAJU|',
'Strachy na Lachy i Itsmisslilly|OBŁĄKANY OBŁOK|',
'Swiernalis|VULGAR|',
'Swiernalis i Piotr Rogucki|OGRODNIK|',
'Syny|BLUZY KAPTURY|',
'Syny|NAG CHAMPA|',
'Syny|Z BIAŁASAMI|',
'Szczyl|PROMIL|',
'Szczyl feat. Magiera|HIPHOPKRYTA|',
'Szczyl feat. Piotr Rogucki|CIEŃ|',
'Szymon Mika|TOGETHERNESS|',
'Szymon Mika i Yumi Ito|FLOAT AND DRIFT|',
'Szymon Mika i Yumi Ito|LONGING|',
'Taco Hemingway|6 ZER|',
'Taco Hemingway|DESZCZ NA BETONIE|',
'Taco Hemingway|MARSZ, MARSZ|',
'Taco Hemingway|NASTĘPNA STACJA|',
'Taco Hemingway|POLSKIE TANGO|',
'Taconafide i Dawid Podsiadło|TAMAGOTCHI|',
'Tankograd|POLSKA|',
'Tede|DYSKRETNY CHŁÓD|',
'Ten Typ Mes|DWADZIEŚCIA PIĘĆ|',
'Ten Typ Mes|KULE Z BUKSZPANU|',
'Ten Typ Mes|TRZE’A BYŁO|',
'Ten Typ Mes i Dawid Podsiadło|CODZIENNOŚĆ|',
'Ten Typ Mes i Justyna Święs|ODPORNOŚĆ|',
'The Car Is On Fire|"CANT COOK (WHO CARES?)"|',
'The Car Is On Fire|CRANKS|',
'The Car Is On Fire|NEWYORKEWR|',
'The New Years 2002 feat. Organek i Bela Komoszyńska|MMB|',
'The Shipyard|DOWNTOWN 2010|',
'The Stubs|A NATION OF LOSERS|',
'The Stubs|SOCIAL DEATH BY ROCK’N’ROLL|',
'The Stubs|YOUNG FOR LIFE|',
'Tides From Nebula|DOPAMINE|',
'Tides From Nebula|GHOST HORSES|',
'Tides From Nebula|TRAGEDY OF JOSEPH MERRICK|',
'Tomasz Dąbrowski i The Individual Beings|FOLLOW HIM|',
'Tomek Makowiecki|HOLIDAYS IN ROME|',
'Tomek Makowiecki|NA SZLAKU NOCNYCH NIEDOPAŁKÓW|',
'Tomek Makowiecki|OSTATNIE WSPÓLNE ZDJĘCIE|',
'Totentanz|ZIMNY DOM|',
'Truchło Strzygi|BUSOLA DO NIKĄD|',
'Truchło Strzygi|OSTATNIE TCHNIENIE NOSFERATU|',
'Trupa Trupa|MOVING|',
'Trupa Trupa|TWITCH|',
'Tulia|JESZCZE CIĘ NIE MA|',
'Tymon i Transistors|BIAŁY MIŚ|',
'Tymon i Transistors|HELP ME OUT|',
'Uniatowski|HONOLULU|',
'Uniatowski|KAŻDEMU WOLNO KOCHAĆ|',
'Vavamuffin|JAH JEST PREZYDENTEM|',
'Vito Bambino|BUNKRÓW NIE MA|',
'VNM|TO MÓJ CZAS|',
'Waglewski Fisz Emade|MĘSKA MUZYKA|',
'Waglewski Fisz Emade|POCISK|',
'Waglewski Fisz Emade|ZIEMIA|',
'WaluśKraksaKryzys|NAJGORSZE RZECZY|',
'WaluśKraksaKryzys|TO CO MIĘDY NAMI|',
'WaluśKraksaKryzys|TUŻ PRZED PÓŁNOCĄ|',
'Wczasy|DZISIAJ JESZCZE TAŃCZĘ|',
'WERK feat. Anita Lipnicka|LULA|',
'Wij|CZERW|',
'Wij|DZIWIDŁO|',
'Włodi|THC|',
'Wojtek Mazolewski i Justyna Święs|ORGANIZMY PIĘKNE|',
'Wojtek Mazolewski Quintet|BANGKOK|',
'Wojtek Mazolewski Quintet|LONDON|',
'Wojtek Mazolewski Quintet|NIONIO|',
'Wojtek Mazolewski Quintet|WOJTEK W CZECHOSŁOWACJI|',
'xxanaxx|STORY|',
'xxanaxx|STYROPIAN|',
'xxanaxx feat. Ten Typ Mes|NIE ZNAJDZIESZ MNIE|',
'Yugoton|MALCZIKI|',
'Yugoton i Maciej Maleńczuk|OSTATNIA NOCKA|',
'Yumi Ito|LITTLE THINGS|',
'Yumi Ito|WHAT SEEMS TO BE|',
'Zakopower|BOSO|',
'Zakopower|BÓG WIE GDZIE|',
'Zdechły Osa|PATOLOVE|',
'Zdechły Osa|ZAKOCHAŁEM SIĘ W TWOJEJ MATCE|',
'Zgredybillies|CAŁE ŻYCIE NA KREDYCIE|',
'Żurkowski feat. Organek|WESTERN|'
]
